name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Zip Bootstrap
        run: zip -r bootstrap.zip bootstrap.*
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: bootstrap.zip
