name: CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

  workflow_dispatch:

jobs:
  test_pwsh:
    name: Unit and Integration Tests (Powershell 7.x)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: install tools and run selftests
        run: |
          Write-Output $PSVersionTable
          .\tests\bin\init.ps1
          .\tests\bin\test.ps1
        shell: pwsh
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          files: |
            tests/out/TestResults.xml
  test_powershell:
    name: Unit and Integration Tests (Powershell 5.x)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: install tools and run selftests
        run: |
          Write-Output $PSVersionTable
          .\tests\bin\init.ps1
          .\tests\bin\test.ps1
        shell: powershell
