name: selftests

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

  workflow_dispatch:

jobs:
  test:
    name: PowerShell
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: install tools and run selftests
        run: |
          .\tests\bin\init.ps1
          .\tests\bin\test.ps1
        shell: pwsh
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          files: |
            tests/out/TestResults.xml
